// English translations for localization messages (categorized, based on ru.lang.js structure)
// Английские переводы локализации сообщений (с категоризацией)
module.exports = {
  behance_profile_set: '✅ **Behance profile set**\n\nYour username: {username}',
  dribbble_profile_set: '✅ **Dribbble profile set**\n\nYour username: {username}',
  artstation_profile_set: '✅ **ArtStation profile set**\n\nYour username: {username}',
  dprofile_profile_set: '✅ **Dprofile profile set**\n\nYour username: {username}',
  invalid_username_format: '❌ Invalid username format. Please try again.',

  // ОСНОВНЫЕ СООБЩЕНИЯ И МЕНЮ
  general: {
    welcome: '🤝 **Designers Mutual Support on DesignLike**\n\n🎨 Behance | Dribbble | ArtStation | Dprofile\n\n🔥 Mutual promotion system: helping each other grow!\n• Publish your projects and get community support\n• Earn 💎 crystals for completing tasks\n• Exchange likes, follows, and comments\n\n⚠️ IMPORTANT: All actions are verified! Violators get blocked.\n\n🚀 Get started now - add your first project and get support!\n\nChoose action:',
    start_command: '🏠 Main Menu\n\nChoose action:',
    user_registered: 'Register with /start first',
    balance: 'Your crystals 💎: {credits}\n\nBuy crystals 💎:',
    add_project_request: 'Send a link to your project (Behance, Dribbble, ArtStation):',
    invalid_url: 'Invalid link. Make sure the link leads to a profile, project or work on Behance, Dribbble or ArtStation.',
    banned_user: '🚫 **Your account is blocked**\n\nReason: Multiple violations of mutual support rules.\n\nIf you believe the blocking is unfair, contact the administrator.\n\nYou can apply for unblocking.',
    perform_action_instruction: '🎯 **To earn crystals 💎 perform the action:**\n\n{action_type} on the project below:\n\n🔗 {url}\n\n⚠️ **IMPORTANT:** Perform a genuine {action_word} on the platform!\n\nAfter performing the action, click "Confirm Execution"',
    project_not_found: 'Project not found',
    self_project_action: 'You cannot perform actions on your own project',
    delete_project_confirm: '⚠️ **Delete Project Confirmation**\n\n🔗 {url}\n\n‼️ **This action cannot be undone!**\nWill be deleted:\n• Project\n• All completed actions for it\n• Created complaints\n\nDelete project?',
    settings: '⚙️ Settings\n\nHere you can configure your profile for full system usage.',
    profile_settings: '🔗 **Profile Setup**\n\nConnect your platform profiles for automatic like verification:\n\nCurrent profiles:\n• Behance: {behance}\n• Dribbble: {dribbble}\n• ArtStation: {artstation}\n• Dprofile: {dprofile}',
    select_language: '🌍 **Choose Interface Language**\n\nSelect your preferred language for the bot interface:',
    language_set: '✅ Language set to: {language}',

    // Additional common keys
    all_tasks_completed: '🎯 **All available tasks completed!**\n\nAdd your project to start receiving mutual support from other users.\n\n💡 The more projects you add, the more people will help with your likes and follows!',
    setup_profiles_warning: '⚠️ **Profile Setup**\n\nTo get access to mutual support tasks, set up your profiles on the platforms first!\n\nAdd links to your Behance, Dribbble, ArtStation, or Dprofile accounts in settings.'
  },

  // Common translations (icons, shared keys)
  common: {
    views_icon: '👀',
    likes_icon: '❤️',
    comments_icon: '💬',
    follows_icon: '👥',
    adding_project: '🏗️ Adding project',
    platform_label: 'Platform: {platform}',
    your_balance: 'Your balance: {credits} 💎',
    select_actions: 'Select actions:',
    total_to_pay: 'Total to pay: {total} 💎',
    add_project_confirm: '✅ Add project',
    cancel_add_project: '❌ Cancel'
  },

  // PROJECTS
  projects: {
    add_project_request: 'Send a link to your project (Behance, Dribbble, ArtStation):',
    invalid_url: 'Invalid link. Make sure the link leads to a profile, project or work on Behance, Dribbble or ArtStation.',
    project_added_success: '✅ Project added successfully!\n\n🎉 Bought actions: {views} views, {likes} likes, {comments} comments, {follows} follows\n💰 Spent: {total} 💎\n\nProject will soon appear in the list for mutual likes!',
    add_project_error: '❌ Error adding project.',
    cancel_add_project: '❌ Project addition cancelled.',
    project_cancelled: '❌ Project addition cancelled.',
    project_not_found: 'Project not found',
    delete_project_confirm: '⚠️ **Delete Project Confirmation**\n\n🔗 {url}\n\n‼️ **This action cannot be undone!**\nWill be deleted:\n• Project\n• All completed actions for it\n• Created complaints\n\nDelete project?',
    confirm_delete_project: '⚠️ **Delete Project Confirmation**\n\n🔗 {url}\n\n‼️ **This action cannot be undone!**\n• Will be deleted: project\n• All completed actions\n• Created complaints\n\nDelete project?',
    yes_delete: '✅ Yes, delete',
    cancel: '❌ Cancel',
    project_deleted: '✅ **Project successfully deleted!**\n\nAll related data have been deleted.',
    delete_project_success: '✅ **Project successfully deleted!**\n\nAll related data have been deleted.',
    delete_project_error: '❌ Error deleting project. Try again later or contact administrator.',
    action_processing_error: '❌ Error processing {operation} on project.',
    delete_error_project_not_found: '❌ Error: project to delete not found.',
    delete_error_no_rights: '❌ Error: project not found or no rights.',
    no_access: '❌ You don\'t have rights to delete this project.',
    project_info: '🎨 **Project:** {url}\n\n📊 Actions completed: {actions}\n📅 Added: {date}',
    project_task_info: '🎯 **{actionVerb} project**\n\n🔗 {url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {actionWord} on the platform',
    project_title: '🎨 Project:',
    completed_actions: '📊 Completed actions:',
    added_date: '📅 Added:',
    delete_confirm_title: '⚠️ Delete confirmation',
    delete_confirm_text: 'This action cannot be undone',
    delete_affects: 'Will be deleted: project, all actions, complaints',
    delete_yes: '✅ Yes, delete',
    delete_cancel: '❌ Cancel',
    delete_success: '✅ Project deleted successfully',
    delete_error: '❌ Deletion error',
    no_projects: '📂 You have no projects yet.\n\nAdd your first project using the ➕ **Add Project** button!',
    no_projects_text: '📂 You have no projects yet.\n\nAdd your first project using the ➕ **Add Project** button!',
    project_list_info: '🎨 **Project:** {url}\n   📊 Actions completed: {actions}\n   📅 Added: {date}\n\n',
    project_detail: '🎨 **Project:** {url}\n\n📊 Actions completed: {actions}\n📅 Added: {date}',
    data_not_found: '❌ Project data not found.',
    view_performers: '🚹 Project performers {num}',
    delete_project: '🚫 Delete project {num}',
    back_to_projects: '🔙 Back to projects',
    back_to_main: '🔙 Back to main menu',
    performers_list_caption: '📋 No one has performed actions on this project yet.',
    performer_action: '{index}. {action} from {username}\n{platform_username}',
    actions_name: 'Like,Follow,Comment,View',
    view_performers_button: '🚹 View performers',
    delete_project_button: '❌ Delete project',
    back_to_main: '🔙 Back to main menu',
  go_to_settings: '⚙️ Go to settings',
  add_project_button: '➕ Add project',
  setup_profiles_warning: '⚠️ **Profile Setup**\n\nTo get access to mutual support tasks, set up your profiles on the platforms first!\n\nAdd links to your Behance, Dribbble, ArtStation, or Dprofile accounts in settings.',
  all_tasks_completed: '🎯 **All available tasks completed!**\n\nAdd your project to start receiving mutual support from other users.\n\n💡 The more projects you add, the more people will help with your likes and follows!',
  no_access_project: '❌ You don\'t have access to this project.'
  },

  // TASKS AND ACTIONS
  tasks: {
    perform_action_instruction: '🎯 **To earn crystals 💎 perform the action:**\n\n{action_type} on the project below:\n\n🔗 {url}\n\n⚠️ **IMPORTANT:** Perform a genuine {action_word} on the platform!\n\nAfter completing the action, click "Confirm Execution"',
    project_task_info: '🎯 **{actionVerb} project**\n\n🔗 {url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {actionWord} on the platform',
    task_instruction: '🎯 **{action_verb} the project**\n\n🔗 {project_url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {action_word} on the platform!',
    dynamic_task_instruction_template: '🎯 **{actionVerb} the project**\n\n🔗 {projectUrl}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {actionWord} on the platform!',
    task_instruction_template: '🎯 **{actionVerb} the project**\n\n🔗 {url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {actionWord} on the platform!',
    view_project_instruction: '🎯 **View the project**\n\n🔗 {url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {actionWord} on the site',
    like_project_instruction: '🎯 **Like the project**\n\n🔗 {url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {actionWord} on the platform!',
    view_project_instruction_ru: '🎯 **View the project**\n\n🔗 {project_url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {action_word} on the site',
    view_project_task_instruction: '🎯 **View the project**\n\n🔗 {project_url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {actionWord} on the site',
    perform_action_instruction: '🎯 **{action_type} on the project**\n\n{action_type}: {url}\n\n💰 +{credits} 💎 after completion\n\n⚠️ Mandatory genuine {action_word} on the platform!',
    action_word_like: 'like',
    action_word_follow: 'follow',
    action_word_comment: 'comment',
    action_word_view: 'view',
    action_verb_like: 'Like',
    action_verb_follow: 'Follow',
    action_verb_comment: 'Leave a comment',
    action_verb_view: 'View',
    action_like: '❤️ Like',
    action_follow: '👥 Follow',
    action_comment: '💬 Comment',
    action_view: '👀 View Project',
    put_like: 'Put like',
    subscribe: 'Subscribe',
    leave_comment: 'Leave comment',
    view_project: 'View project',
    count_views: 'views',
    count_likes: 'likes',
    count_comments: 'comments',
    count_follows: 'follows',
    select_count: 'Great! Now specify the number of {type} (1-1000):',
    count_type_error: '❌ Enter correct number of {type} (1-1000):',
    at_least_one_action: '❌ Select at least one action (views, likes, comments or follows).',
    confirm_execution: '✅ Confirm execution',
    confirm_execution_button: '✅ Confirm execution',
    thank_you_action: '✅ Thank you for mutual support!\n\n💰 +{credits} {unit} credited for {action}!',
    thanks_for_support: '✅ Thank you for mutual support!\n\n💰 +{credits} {unit} credited for {action}!',
    thank_you_mutual: '✅ Thank you for mutual support!\n\n💰 +{credits} {unit} credited for {action}!',
    self_project_action: 'You cannot perform actions on your own project',
    own_project_action: 'You cannot perform actions on your own project',
    action_already_done: '⚠️ This action has already been performed.',
    action_already_done: '⚠️ Action already done',
    action_already_performed: '⚠️ This action has already been performed.',
    action_error: '❌ Error processing {action}. Try again later.',
    error_action: '❌ Error executing action',
    action_completed: '✅ Action confirmed',
    action_already_done: '⚠️ Action already done',
    loading_next_task: '⏳ Loading next task...',
    follow_limit_reached: '⚠️ You have already followed this profile in the last 30 days. Repeat follows to the same URL are not allowed.',
    follow_limit_exceeded: '⚠️ You have already followed this profile in the last 30 days. Repeat follows to the same URL are not allowed.',
    view_word: 'View',
    like_word: 'Like',
    follow_word: 'Follow',
    comment_word: 'Comment',
    real_action_required: 'real {action}',
    complete_action: 'Perform real {action} on the platform',
    return_to_task: '🔙 Back to task'
  },

  // LEVELS
  levels: {
    level_novice: 'Novice',
    level_designer: 'Designer',
    level_profi: 'Pro',
    level_expert: 'Expert',
    level_novice_emoji: '🌱',
    level_designer_emoji: '🎨',
    level_profi_emoji: '🏆',
    level_expert_emoji: '🚀',
    level_title: '{name} level',
    rating_label: 'Rating',
    progress_to_level: '⭐ Progress to level "{next}": {progress}/{max} ({percentage}%)',
    max_level_achieved: '⭐ Maximum level achieved!',
    progress_title: 'Progress to level "{next}": {progress}/{max} ({percentage}%)',
    progress_completed: 'Maximum level achieved!'
  },

  // ACHIEVEMENTS
  achievements: {
    achievement_active: '🏃‍♂️ Active participant (+5 tasks)',
    achievement_honest: '🛡️ Honest designer (no warnings)',
    achievement_creative: '📂 Creative ({count} projects)',
    achievement_rich: '💎 Rich designer ({count} 💎)',
    achievement_business: '💰 Business designer ({count} 💎 spent)',
    achievement_social: '🧑‍🤝‍🧑 Social ({count} people helped)',
    achievement_expert: '🌟 Expert (reached maximum level)',
    achievement_veteran: '⚡ Veteran ({count} days active)',
    achievement_general: '🏅 General ({count} actions received)',
    achievement_behance: '🎨 Behance expert ({count} on Behance)',
    achievement_dribbble: '🎯 Dribbble expert ({count} on Dribbble)',
    achievement_artstation: '✨ ArtStation expert ({count} on ArtStation)',
    achievement_novice: '🌱 Novice (start completing tasks)',
    active_participant_achievement: '🏃‍♂️ Active participant (+5 tasks)',
    honest_designer_achievement: '🛡️ Honest designer (no warnings)',
    creative_achievement: '📂 Creative ({count} projects)',
    rich_designer_achievement: '💎 Rich designer ({count} 💎)',
    business_designer_achievement: '💰 Business designer ({count} 💎 spent)',
    social_achievement: '🧑‍🤝‍🧑 Social ({count} people helped)',
    expert_achievement: '🌟 Expert (reached maximum level)',
    veteran_achievement: '⚡ Veteran ({count} days active)',
    general_achievement: '🏅 General ({count} actions received)',
    behance_expert_achievement: '🎨 Behance expert ({count} on Behance)',
    dribbble_expert_achievement: '🎯 Dribbble expert ({count} on Dribbble)',
    artstation_expert_achievement: '✨ ArtStation expert ({count} on ArtStation)',
    novice_achievement: '🌱 Novice (start completing tasks)'
  },

  // RATING
  rating: {
    rating_points: 'points',
    days_system: 'in system',
    reliability_high: 'High ✅',
    reliability_medium: 'Medium ⚠️',
    reliability_low: 'Low ❌',
    rating_section_title: '⭐ Progress to level "{next}": {progress}/{max} ({percentage}%)',
    rating_section_completed: '⭐ Maximum level achieved!',
    rating_section_stats: '📈 **Activity statistics:**\n• Tasks completed: {sent}\n• People helped by your projects: {received}\n• Projects added: {projects}\n• Reliability: {reliability}',
    rating_section_achievements: '🏆 **Achievements:**{achievements}',
    rating_section_main: '🗓️ In system {days} {days_word}',
    activity_stats: '📈 **Activity statistics:**\n• Tasks completed: {sent}\n• People helped by your projects: {received}\n• Projects added: {projects}\n• Reliability: {reliability}',
    in_system_days: '🗓️ In system {days} {days_word}',
    days_system: 'in system',
    days_nominative: 'days',
    days_genitive: 'days',
    day_singular: 'day',
    days_nominative: 'days'
  },

  // SETTINGS
  settings: {
    settings: '⚙️ Settings\n\nHere you can configure your profile for full system usage.',
    profile_settings: '🔗 **Profile Setup**\n\nConnect your profiles on platforms for automatic like verification:\n\nCurrent profiles:\n• Behance: {behance}\n• Dribbble: {dribbble}\n• ArtStation: {artstation}\n• Dprofile: {dprofile}',
    settings_profiles_menu: '🔗 **Profile Setup**\n\nConnect your profiles on platforms for automatic like verification:\n\nCurrent profiles:\n• Behance: {behance}\n• Dribbble: {dribbble}\n• ArtStation: {artstation}\n• Dprofile: {dprofile}',
    view_profiles_message: '👀 **Your connected profiles**\n\n*Behance:* {behance}\n*Dribbble:* {dribbble}\n*ArtStation:* {artstation}\n\nConnect your profiles for like verification via API.',
    select_language: '🌍 **Choose Interface Language**\n\nSelect your preferred language for the bot interface:',
    language_set: '✅ Language set to: {language}',
    language_selected_ru: '✅ Russian language selected!\n\nChoose "Continue" to start working.',
    language_selected_en: '✅ English language selected!\n\nChoose "Continue" to start working.',
    continue: 'Continue',
    continue_en: 'Continue',
    behance_profile_setup_prompt: '🎨 **Behance Profile Setup**\n\nEnter your Behance username (profile name after behance.net/).\n\nExample: for https://www.behance.net/alexdesign enter: **alexdesign**\n\nOr specify the full profile URL.',
    dribbble_profile_setup_prompt: '🎯 **Dribbble Profile Setup**\n\nEnter your Dribbble username (profile name after dribbble.com/).\n\nExample: for https://dribbble.com/alexdesign enter: **alexdesign**\n\nOr specify the full profile URL.',
    artstation_profile_setup_prompt: '✨ **ArtStation Profile Setup**\n\nEnter your ArtStation username (profile name after artstation.com/).\n\nExample: for https://www.artstation.com/alexdesign enter: **alexdesign**\n\nOr specify the full profile URL.',
    dprofile_profile_setup_prompt: '📰 **Dprofile Profile Setup**\n\nEnter your Dprofile username (profile name after dprofile.ru/).\n\nExample: for https://dprofile.ru/alexdesign enter: **alexdesign**\n\nOr specify the full profile URL.',

    no_platforms_warning: '🔗 **To get access to tasks from other users, set up your platform profiles!**\n\nGo to ⚙️ Settings -> 🔗 Set up profiles and specify your Behance, Dribbble or ArtStation accounts.\n\nThis will allow you to interact with tasks on these platforms.',
    no_tasks_available: 'No available tasks for your linked platforms right now. Add your project first so that others can complete your tasks.',
    important_warning: '⚠️ **IMPORTANT:** To get 💎 crystals, you MUST leave a real like/follow/comment on the platform site (Behance/Dribbble/ArtStation).\n\nThe system is based on mutual trust. Breaking the rules will result in blocking.',
    balance: '💰 Balance',
    keyboard_balance: '💰 Balance',
    set_profiles_button: '🔗 Set up profiles',
    change_language_button: '🌍 Change language',
    change_profiles_button: '🔗 Change profiles',
    back_to_settings_button: '🔙 Back to settings',
    russian_button: '🇷🇺 Russian',
    english_button: '🇺🇸 English'
  },

  // BUTTONS AND KEYBOARDS
  buttons: {
    available_tasks: '🎯 Available Tasks',
    add_project: '➕ Add Project',
    my_projects: '📂 My Projects',
    my_rating: '📈 My Rating',
    balance: '💰 Balance',
    settings: '⚙️ Settings',
    admin_panel: '🏛️ Admin Panel',
    back_to_main: '🔙 Back to main menu',
    send_project_url: 'Send project link',
    invalid_format: 'Invalid format',
    enter_correct_number: 'Enter correct number',
    send_full_url: 'Send full link',
    insufficient_funds: 'Insufficient crystals',
    project_added: '✅ Project added',
    project_cancelled: '❌ Cancelled',
    open_project_button: '🔗 Open project',
    confirm_execution_button: '✅ Confirm execution',
    complain_button: '🚨 Report',
    view_performers_button: '🚹 View performers',
    delete_project_button: '❌ Delete project',
    go_back: '🔙 Back',
    buy_crystals: 'Buy crystals 💎',
    buy_button: '💎 Buy',
    open_project: '🔗 Open project',
    report_complaint: '🚨 Report',
    behance_profile_button: '🎨 Behance Profile',
    dribbble_profile_button: '🎯 Dribbble Profile',
    artstation_profile_button: '✨ ArtStation Profile',
    dprofile_profile_button: '📰 Dprofile Profile',
    view_profiles_button: '👀 View My Profiles',
    back_button: '🔙 Back',
    complaint_opened: '🔗 Open project',
    complain_button: '🚨 Report',
    complaint_submitted: '✅ Complaint submitted!\n\nPerformer deleted from project, repeat complaint impossible. Admin will review violation.',
    complaint_handled: '❌ You don\'t have rights to this operation.',
    complaint_auto_message: 'Automatic complaint through project: {url}',
    go_to_settings: '⚙️ Go to settings',
    add_project_button: '➕ Add project',
    complain_violation: '🚨 Report violation',
    main_menu_keyboard: [['🎯 Available Tasks', '➕ Add Project'], ['📈 My Rating', '💰 Balance'], ['⚙️ Settings']],
    main_menu_keyboard_admin: [['🎯 Available Tasks', '➕ Add Project'], ['📈 My Rating', '💰 Balance'], ['📊 Statistics', '⚙️ Settings'], ['🏛️ Admin Panel']],
    banned_keyboard: [['🔓 Submit unblock request']],
    keyboard_unblock_request: '🔓 Submit unblock request',
    keyboard_available_tasks: '🎯 Available Tasks',
    keyboard_add_project: '➕ Add Project',
    keyboard_referrals: '🤝 Referrals',
    keyboard_my_projects: '📂 My Projects',
    keyboard_rating: '📈 My Rating',
    keyboard_balance: '💰 Balance',
    keyboard_settings: '⚙️ Settings',
    keyboard_admin_panel: '🏛️ Admin Panel',
    admin_view_complaints: '📋 View complaints',
    admin_broadcast: '📤 Broadcast',
    admin_ban_user: '🚫 Ban user',
    admin_unban_user: '🔓 Unban user',
    admin_stats: '📊 Bot statistics',
    yes_delete: '✅ Yes, delete',
    cancel: '❌ Cancel',
    back_to_main: '🔙 Back to main menu',
    go_to_settings: '⚙️ Go to settings',
    add_project_button: '➕ Add project',
    complain_violation: '🚨 Report violation',
    buy_100_crystals: '100 💎 - 100 ₽',
    buy_500_crystals: '500 💎 - 450 ₽ (discount)',
    buy_1000_crystals: '1000 💎 - 850 ₽ (discount)',
    send_broadcast: '📤 Send Broadcast',
    cancel_broadcast: '❌ Cancel',
    decline_unblock: '❌ Decline',
    adding_project: '🏗️ Adding project',
    platform_label: 'Platform: {platform}',
    your_balance: 'Your balance: {credits} 💎',
    select_actions: 'Select actions:',
    views_icon: '👀',
    likes_icon: '❤️',
    comments_icon: '💬',
    follows_icon: '👥',
    total_to_pay: 'Total to pay: {total} 💎',
    add_project_confirm: '✅ Add project',
    cancel_add_project: '❌ Cancel'
  },

  // COMPLAINTS
  complaints: {
    report_complaint: '🚨 Report',
    complaint_opened: '🔗 Open project',
    complain_button: '🚨 Report',
    complaint_submitted: '✅ Complaint submitted!\n\nPerformer deleted from project, repeat complaint impossible. Admin will review violation.',
    complaint_handled: '❌ You don\'t have rights to this operation.',
    complaint_auto_message: 'Automatic complaint through project: {url}',
    complaint_notification_admin: '🚨 **New complaint from project owner**\n\n👤 **Owner:** @{complainant_user} (@{complainant_id})\n😤 **Performer:** @{performer_user} (@{performer_id})\n\n📱 **Username to check:** {platform_username}\n\n🔗 **Project:** {project_url}\n📝 **Reason:** {complaint_type}\n📅 **Transaction date:** {transaction_date}',
    admin_complaints_list: '📋 **Pending complaints:**\n\nChoose complaint to review:',
    complaints_none: '✅ No new complaints.',
    admin_complaints_none: '✅ No new complaints.',
    complaint_detail: '🚨 **Complaint details #{complaint_id}**\n\n👤 **Project owner:** {complainant_name} (@{complainant_id})\n😤 **Accused performer:** {reported_name} (@{reported_id})\n\n📱 **Username to check on {platform}:** {platform_username}\n\n🔗 **Project:** {project_url}\n📝 **Reason:** {complaint_reason}\n📅 **Date:** {complaint_date}',
    complaint_not_found: '❌ Complaint not found.',
    admin_complaint_detail: '🚨 **Complaint details #{complaintId}**\n\n👤 **Project owner:** {complainantName} (@{complainantId})\n😤 **Accused performer:** {reportedName} (@{reportedId})\n\n📱 **Username to check on {platform}:** {platformUsername}\n\n🔗 **Project:** {projectUrl}\n📝 **Reason:** {complaintReason}\n📅 **Date:** {complaintDate}',
    complaint_not_found_admin: '❌ Complaint not found.',
    back_to_complaints: '🔙 Back to complaints',
    back_to_complaints_list: '🔙 Back to list',
    admin_action_first_warn: '⚠️ First warning issued to performer.',
    admin_action_second_warn: '⚠️ Second warning issued to performer.',
    admin_action_ban: '🚫 Performer banned for multiple violations.',
    admin_action_first_warning: '⚠️ First warning issued to performer.',
    admin_action_second_warning: '⚠️ Second warning issued to performer.',
    admin_action_user_banned: '🚫 Performer banned for multiple violations.',
    complaint_notification_complainant: '🛡️ **Complaint reviewed**\n\n❌ **Admin decision:** Complaint rejected, no violation found\n\n➡️ **Action from:** {target_user}\n💬 **Reason:** {complaint_reason}\n🔗 **Project:** {project_url}',
    complaint_warning_first: '⚠️ **Warning for rule violation**\n\n👤 **Reason:** {complaint_reason}\n🔗 **Project:** {project_url}\n\n⚠️ **This is the first warning.** You will receive a second warning for repeat violation, and third will result in account blocking.',
    complaint_warning_second: '⚠️ **Second warning for violation**\n\n👤 **Reason:** {complaint_reason}\n🔗 **Project:** {project_url}\n\n⚠️ **This is the second warning.** Your account will be blocked upon next violation!\n\nPlease follow mutual support rules.',
    complaint_resolution_ban: '✅ **Complaint satisfied**\n\n🚫 **Admin decision:** Performer violated rules three times, {user} banned\n\n💬 **Complaint reason:** {complaint_reason}\n🔗 **Project:** {project_url}',
    complaint_resolved: '✅ Complaint rejected, notifications sent to participants.',
    complaint_handled: '{text} Notifications sent.',
    complaint_notification_error: '❌ Error sending notifications.',
    complaint_resolution_rejected_complainant: '🛡️ **Complaint reviewed**\n\n❌ **Admin decision:** Complaint rejected, no violations found\n\n➡️ **Action from:** {reportedUser}\n💬 **Reason:** {reason}\n🔗 **Project:** {projectUrl}',
    complaint_resolution_first_warning_complainant: '✅ **Complaint reviewed**\n\n⚠️ **Admin decision:** Violation confirmed, first warning issued to performer\n\n💬 **Complaint reason:** {reason}\n🔗 **Project:** {projectUrl}',
    complaint_resolution_second_warning_complainant: '✅ **Complaint reviewed**\n\n⚠️ **Admin decision:** Violation confirmed, second warning issued to performer\n\n💬 **Complaint reason:** {reason}\n🔗 **Project:** {projectUrl}',
    complaint_resolution_satisfied_complainant: '✅ **Complaint satisfied**\n\n🚫 **Admin decision:** Performer violated rules three times, {reportedUser} banned\n\n💬 **Complaint reason:** {reason}\n🔗 **Project:** {projectUrl}',
    complaint_notification_to_complainant: '🛡️ **Complaint reviewed**\n\n❌ **Admin decision:** Complaint rejected, {user} did not find violation\n\n➡️ **Action from:** {target}\n💬 **Reason:** {reason}\n🔗 **Project:** {url}',
    complaint_notification_first_warn: '✅ **Complaint reviewed**\n\n⚠️ **Admin decision:** Violation confirmed, first warning issued to performer\n\n💬 **Complaint reason:** {reason}\n🔗 **Project:** {url}',
    complaint_warning_text_first: '⚠️ **Warning for rule violation**\n\n👤 **Reason:** {reason}\n🔗 **Project:** {url}\n\n⚠️ **This is the first warning.** You will receive a second warning for repeat violation, and third will result in account blocking.',
    complaint_warning_text_second: '⚠️ **Second warning for violation**\n\n👤 **Reason:** {reason}\n🔗 **Project:** {url}\n\n⚠️ **This is the second warning.** Your account will be blocked upon next violation!\n\nPlease follow mutual support rules.',
    complaint_ban_text: '🚫 **Your account blocked for multiple violations**\n\n⚠️ **Reason:** {reason}\n👤 **Complained by:** {complainant}\n🔗 **Project:** {url}\n\nThis is third violation. If you consider blocking unfair, contact administrator.\n\nYou can apply for unblocking below.',
    complaint_resolution_text: '✅ **Complaint satisfied**\n\n🚫 **Admin decision:** Performer violated rules three times, {user} banned\n\n💬 **Complaint reason:** {reason}\n🔗 **Project:** {url}',
    complaint_warning_first_user: '⚠️ **Warning for rule violation**\n\n👤 **Reason:** {reason}\n🔗 **Project:** {projectUrl}\n\n⚠️ **This is the first warning.** You will receive a second warning for repeat violation, and third will result in account blocking.\n\nPlease follow mutual support rules.',
    complaint_warning_second_user: '⚠️ **Second warning for violation**\n\n👤 **Reason:** {reason}\n🔗 **Project:** {projectUrl}\n\n⚠️ **This is the second warning.** Your account will be blocked upon next violation!\n\nPlease follow mutual support rules.',
    complaint_processing_error: '❌ Error processing complaint.'
  },

  // ADMIN
  admin: {
    admin_panel: '🏛️ **Admin Panel**\n\nChoose action to manage the bot:',
    admin_panel_short: '🏛️ **Admin Panel**\n\nChoose action:',
    admin_panel_title: '🏛️ **Admin Panel**\n\nChoose action:',
    final_admin_panel_message: '🏛️ **Admin Panel**\n\nChoose action:',
    admin_view_complaints: '📋 View complaints',
    admin_broadcast: '📤 Broadcast',
    admin_ban_user: '🚫 Ban user',
    admin_unban_user: '🔓 Unban user',
    admin_stats: '📊 Bot statistics',
    admin_new_complaint: '🚨 **New complaint from project owner**\n\n👤 **Owner:** @{complainantUser} (@{complainantId})\n😤 **Performer:** @{performerUser} (@{performerId})\n\n📱 **Username to check:** {platformUsername}\n\n🔗 **Project:** {projectUrl}\n📝 **Reason:** {complaintType}\n📅 **Transaction date:** {transactionDate}',
    admin_complaints_none: '✅ No new complaints.',
    admin_complaints_list: '📋 **Pending complaints:**\n\nChoose complaint to review:',
    admin_complaint_detail: '🚨 **Complaint details #{complaintId}**\n\n👤 **Project owner:** {complainantName} (@{complainantId})\n😤 **Accused performer:** {reportedName} (@{reportedId})\n\n📱 **Username to check on {platform}:** {platformUsername}\n\n🔗 **Project:** {projectUrl}\n📝 **Reason:** {complaintReason}\n📅 **Date:** {complaintDate}',
    admin_only_message: 'Use /admin command',
    admin_ban_success: '🚫 User {username} (@{user_id}) banned. Notification sent.',
    admin_ban_error: '❌ Error banning user.',
    admin_ban_user_success: '🚫 User {username} (@{telegramId}) banned. Notification sent.',
    admin_ban_user_error: '❌ Error banning user.',
    admin_action_first_warn: '⚠️ First warning issued to performer.',
    admin_action_second_warn: '⚠️ Second warning issued to performer.',
    admin_action_ban: '🚫 Performer banned for multiple violations.',
    admin_action_first_warning: '⚠️ First warning issued to performer.',
    admin_action_second_warning: '⚠️ Second warning issued to performer.',
    admin_action_user_banned: '🚫 Performer banned for multiple violations.',
    admin_unban_prompt: '🔓 **Unban user**\n\nSend the Telegram ID of the user to unban.',
    admin_ban_format_error: '❌ Invalid user ID format. Use: `123456789 ban reason`',
    admin_user_not_banned: '❌ User not banned.',
    admin_unblock_error: '❌ Invalid user ID format. Provide only Telegram ID.',
    admin_unblock_success: '✅ User {id} unbanned. User notified.',
    admin_unblock_failure: '❌ Failed to unban user {id} ({username}). They may not have been banned.',
    admin_unblock_generic_error: '❌ Error unbanning user.',
    admin_bot_statistics: '📊 **DesignLike Bot Statistics**\n\n👥 **Users:**\n• Total: {totalUsers}\n• Active (this week): {activeUsers}\n• Banned: {bannedUsers}\n\n🎨 **Content:**\n• Projects: {totalProjects}\n• Completed actions: {totalActions}\n\n🛎️ **Complaints:**\n• Total: {totalComplaints}\n• Pending review: {pendingComplaints}\n\n💎 **Economy:**\n• Crystals purchased: {totalCreditsEarned}\n• Spent on projects: {totalCreditsSpent}',
    stats_error: '❌ Error retrieving statistics. Try again later.',
    final_stats_error: '❌ Error retrieving statistics. Try again later.',
    admin_unban_prompt: '🔓 **Unban user**\n\nSend the Telegram ID of the user to unban.',
    unban_success_user: '✅ User {user_id} unbanned. User notified.',
    unban_success_user_action: '✅ User {userId} unbanned. User notified.',
    unban_failure: '❌ Failed to unban user {userId} ({username}). They may not have been banned.',
    unban_failure_user_action: '❌ Failed to unban user {userId} ({username}). They may not have been banned.',
    ban_user_admin_prompt: '🚫 **Ban user**\n\nSend the Telegram ID and ban reason in format:\n`ID reason`\n\nExample: `123456789 Spam`',
    ban_success: '🚫 User {username} (@{id}) banned. Notification sent.',
    ban_success_admin: 'User banned',
    unban_success_admin: 'User unbanned',
    stats_week_actions: '{actions} actions this week',
    complaint_count: 'New complaints: {count}',
    broadcast_text_prompt: '📤 **Broadcast message to all users**\n\nSend the message to be sent to all active users (not banned).\n\n⚠️ **Warning:** Message will be sent immediately!',
    important_banner: '🚨 **Warning!** Message will be sent to ALL active users!\n\n💬 **Message text:**\n{message}\n\nChoose action:',
    broadcast_confirm: '📤 Confirm broadcast',
    admin_broadcast_confirm_long: '📤 **Broadcast Confirmation**\n\n🚨 **Warning!** Message will be sent to ALL active users (not banned)!\n\n💬 **Message text:**\n{message}\n\nChoose action:',
    broadcast_sent_success: '✅ Broadcast completed!\n\n📤 Sent to: {sent} users\n❌ Errors: {errors}\n\n📅 {date}',
    broadcast_error: '❌ Error during broadcast.',
    broadcast_cancelled: '❌ Broadcast cancelled.',
    broadcast_start: '📤 Starting broadcast',
    broadcast_progress: 'Sent: {sent}, Errors: {errors}',
    broadcast_complete: '✅ Broadcast completed',
    broadcast_completion_message: 'Broadcast completed!\n\n📤 Sent: {sentCount} users\n❌ Errors: {errorCount}\n\n📅 {date}',
    message_empty: '❌ Message cannot be empty.',
    broadcast_sent: '📤 Broadcasting...\n\n⏳ Please wait, messages are being sent to users...',
    broadcast_completed: '✅ Broadcast completed!\n\n📤 Sent to: {sent} users\n❌ Errors: {errors}\n\n📅 {date}',
    broadcast_error_generic: '❌ Error during broadcast.',
    unblock_prompt_id: '🔓 **Unban user**\n\nSend the Telegram ID of the user to unban.',
    unblock_id_invalid: '❌ Invalid user ID format. Provide only Telegram ID.',
    unblock_success: '✅ User {id} ({username}) unbanned. User notified.',
    unblock_failure: '❌ Failed to unban user {id} ({username}). They may not have been banned.',
    unblock_error: '❌ Error unbanning user.',
    ban_user_prompt: '🚫 **Ban user**\n\nSend the Telegram ID and ban reason in format:\n`ID reason`\n\nExample: `123456789 Spam`',
    ban_id_invalid: '❌ Invalid user ID format. Use: `123456789 ban reason`',
    admin_unban_prompt: '🔓 **Unban user**\n\nSend the Telegram ID of the user to unban.',
    admin_unban_prompt: '🔓 **Unban user**\n\nSend the Telegram ID of the user to unban.',
    ban_user_format: 'ID reason',
    unban_reject_notification: '❌ User {userId} request rejected. User notified.',
    unban_decline: '❌ User {id} request rejected. User notified.',
    admin_decline_reject: '❌ User {user_id} request rejected. User notified.',
    admin_send_error: '❌ Error sending notification to user.',
    user_unban_request_rejected: '❌ **Unblock request rejected**\n\nYour unblock request has been rejected by the administrator.\n\nIf you think this is unfair, contact the administrator directly.',
    unblock_request_reject: '❌ **Unblock request rejected**\n\nYour unblock request has been rejected by the administrator.\n\nIf you think this is unfair, contact the administrator directly.'
  },

  // PAYMENTS
  payments: {
    buy_crystals: 'Buy crystals 💎',
    buy_button: '💎 Buy',
    balance: '💰 Balance',
    payment_confirmation: 'Confirmation of {amount} 💎 payment for {cost} ₽',
    success_payment: '✅ Payment successful! Credited {amount} 💎.',
    invalid_amount: '❌ Invalid purchase amount.',
    insufficient_funds: 'Insufficient crystals',
    unit_singular: 'credit',
    unit_plural: 'credits',
    unit_plural_2: 'credits',
    unit_plural_genitive: 'credits',
    unit_plural_nominative: 'credits',
    credit_value: 'credit'
  },

  // SYSTEM MESSAGES
  system: {
    command_not_found: 'Command not found',
    access_denied: 'Access denied',
    reg_required: 'Registration required',
    db_error: 'Database error',
    network_error: 'Network problem',
    try_later: 'Try later',
    error_sending_notification: '❌ Error sending notification to user. Bot may be blocked.',
    invalid_amount: '❌ Invalid purchase amount.',
    user_not_registered: 'Register with /start first',
    loading_referrals: '⏳ Loading referral system...',
    error_occurred: '❌ An error occurred. Please try again later.'
  },

  // BAN AND UNBAN
  ban: {
    banned_user: '🚫 **Your account is blocked**\n\nReason: Multiple violations of mutual support rules.\n\nIf you believe the blocking is unfair, contact the administrator.\n\nYou can apply for unblocking.',
    ban_notification_text: '🚫 **Your account has been blocked by administrator**\n\nReason: Violation of system rules.\n\nYou can apply for unblocking below.',
    banned_user_keyboard: '🔓 Submit unblock request',
    banned_message: '🚫 **Your account is blocked**\n\nReason: Multiple violations of mutual support rules.\n\nIf you think the blocking is unfair, contact the administrator.\n\nYou can apply for unblocking.',
    user_account_banned_admin: '🚫 **Your account has been blocked by administrator**\n\nReason: Violation of system rules.\n\nYou can apply for unblocking below.',
    ban_success: '🚫 User {username} (@{id}) banned. Notification sent.',
    ban_success_admin: 'User banned',
    admin_ban_user_success: '🚫 User {username} (@{telegramId}) banned. Notification sent.',
    admin_ban_user_error: '❌ Error banning user.',
    unban_success: '✅ User {id} ({username}) unbanned. User notified.',
    unban_success_user: '✅ User {user_id} unbanned. User notified.',
    unban_success_user_action: '✅ User {userId} unbanned. User notified.',
    unban_failure: '❌ Failed to unban user {userId} ({username}). They may not have been banned.',
    unban_success_admin: 'User unbanned',
    user_not_found_by_id: '❌ User with Telegram ID {id} not found in database.',
    banned_user_welcome_back: '✅ You are not banned. Welcome back!',
    unban_request_duplicate: '⚠️ **You have already submitted a request**\n\n' +
      'You can submit a new request only 24 hours after the previous one.\n' +
      'Please wait.',
    unban_request_success: '✅ **Unblock request sent to admin!**\n\n' +
      'The administrator will review your request soon.\n\n' +
      'If approved, you will access all bot functions.\n\n' +
      'You can submit a new request no earlier than in 24 hours.',
    unban_request_error: '❌ Error sending request. Try again later.',
    unblock_prompt_id: '🔓 **Unban user**\n\nSend the Telegram ID of the user to unban.',
    unblock_id_invalid: '❌ Invalid user ID format. Provide only Telegram ID.',
    unblock_failure: '❌ Failed to unban user {id} ({username}). They may not have been banned.',
    unban_reject_notification: '❌ User {userId} request rejected. User notified.',
    unban_decline: '❌ User {id} request rejected. User notified.',
    admin_decline_reject: '❌ User {user_id} request rejected. User notified.',
    admin_send_error: '❌ Error sending notification to user.',
    user_unban_request_rejected: '❌ **Unblock request rejected**\n\nYour unblock request has been rejected by the administrator.\n\nIf you think this is unfair, contact the administrator directly.',
    keyboard_unblock_request: '🔓 Submit unblock request'
  },

  // ACCESS AND ERRORS
  // REFERRAL SYSTEM
  referals: {
    menu_button: '🤝 Referrals',
    menu_title: '🤝 **Referral System**\n\nInvite friends and get bonuses!\n\n💰 **Your benefits:**\n• +50💎 for each friend registration\n• +20% from all invited earnings\n• +20% from friends\' crystal purchases\n\n📊 **Statistics:**\n🎯 Invited: {total}\n💰 Earned: {earned}💎\n\n🎁 **Your referral link:**',
    copy_link_button: '📋 Copy link',
    invite_friends_button: '👥 Invite friends',
    my_referrals_button: '📋 My invited',
    stats_button: '📈 Statistics',
    share_text: '🎁 I invite you to DesignLike - mutual support system for designers!\n\n💪 You can here:\n• Get free likes/follows/comments\n• Earn 💎 crystals\n• Publish your projects\n\n🔗 Join: {link}',
    no_referrals: '📭 You don\'t have invited friends yet.\n\nSend referral link to friends!\n\n📋 {code}',
    referral_list: '👥 **Your invited** ({count})',
    referral_item: '👤 **{username}** (@id{id}) - invited {date}',
    referral_earn_total: '💰 Total earned from referrals: {amount}💎',
    referral_earn_today: '⭐ Today: +{amount}💎',
    referral_level_bronze: '🥉 Bronze refer (0-99💎)',
    referral_level_silver: '🥈 Silver refer (100-499💎)',
    referral_level_gold: '🥇 Gold refer (500+💎)',
    referral_bonus_registration: '🎉 +{amount}💎 for inviting friend!',
    referral_bonus_earning: '💰 +{amount}💎 referral bonus (20% of earnings)',
    referral_bonus_purchase: '🛒 +{amount}💎 referral bonus (20% of purchase)',
    referral_registration_success: '✅ **You registered via referral link!**\n\n🎁 Referrer gets +50💎\n\nWelcome to DesignLike! 🌟',
    referral_link_copied: '✅ Referral link copied to clipboard!',
    copy_link_template: '🔗 **Your referral link for copying:**\n\n\`{link}\`\n\n📋 Tap the link above to copy it',
    referral_code_applied: '✅ Referral code applied! You will get bonuses when registering.',
    referral_error_code_not_found: '❌ Referral code not found. Check code correctness.',
    referral_error_already_used: '❌ You already have a referrer.',
    referral_error_self_referral: '❌ You cannot invite yourself!',
    keyboard_referral_menu: '🤝 Referral System',
    back_to_referral_menu: '🔙 Back to referrals',
    referral_share_link: '🔗',
    referral_copy_code: 'COPY CODE',
    referral_invite_link: 'INVITE BY LINK',
    referral_invite_code: 'SEND CODE TO FRIEND',
    referral_details: '📊 Referral details',
    new_referral_notification: '🎉 **New referral joining!**\n\n👤 **{username}** registered using your referral link\n📝 **Code:** {referral_code}\n\n💰 **You receive +50 💎** for registration!\n\n🎁 **Invite more friends:**\n{referral_link}'
  },

  access: {
    user_not_found_error: '❌ User not found.',
    data_not_found: '❌ Project data not found.',
    complaint_not_found: '❌ Complaint not found.',
    admin_complaint_not_found: '❌ Complaint not found.',
    invalid_count: '❌ Enter correct number of {type} (1-1000):',
    count_type_error: '❌ Enter correct number of {type} (1-1000):'
  }
};
